name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

env:
  CI_SKIP: false

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, 'doc:')"
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [14.x]
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git log
        shell: bash
        run: |
          if [ -n "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+')" ]; then
            echo '::set-env name=CI_SKIP::true'
          fi

      - name: Setup node@${{ matrix.target }}
        if: "env.CI_SKIP == 'false'"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.target }}

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: List versions
        continue-on-error: true
        if: "env.CI_SKIP == 'false'"
        shell: bash
        run: |
          node -v && npm version && which npm && pwd && npx envinfo

      - name: Install dependencies
        if: "env.CI_SKIP == 'false'"
        run: |
          npm ci --quiet

      - name: Lint
        if: "env.CI_SKIP == 'false'"
        run: |
          npm run lint

      # - name: Build
      #   if: "env.CI_SKIP == 'false'"
      #   run: |
      #     npm run ts && npm run build:config

      # - name: Check build
      #   if: "env.CI_SKIP == 'false'"
      #   shell: bash
      #   run: |
      #     pwd && ls -la

      - name: Run Test
        if: "env.CI_SKIP == 'false'"
        run: |
          npm t

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        if: env.CI_SKIP == 'false' && success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unit_tests
